### PR TITLE
Create 0001-mission-statement.md

### PR DESCRIPTION
**Pull request by rkingsbury**
Materials Project Software Foundation mission statement

### CODE REVIEW

**Comment by jmmshn** [comment]
@rkingsbury can you post a link to the Chan-Zuck paper?

**Comment by JaGeo** [comment]
@jmmshn  https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010627 I still had it open.

**Comment by JaGeo** [comment]
To include the DEI components in our statement: 
could we add inclusive somewhow? I am not sure "inclusive governance" would completely caputure it but maybe we can add it to the "community-driven" part as in "inclusive community"? As English is my second language, I am very open to different suggestions.

**Comment by rkingsbury** [comment]
What about

>community-driven, inclusive, coordinated, transparent, and accountable governance

**Comment by JaGeo** [comment]
Fine from my side. I was just not completely sure whether this would imply that we are working towards an inclusive community.

**Comment by shyuep** [comment]
Fine with me. I agree with @JaGeo that I have no idea what inclusive means in this context. We don't select our community - they basically volunteer their PRs and Issue Reports. In most instances, we do not even know the real identity of our contributors.

**Comment by rkingsbury** [comment]
> Fine from my side. I was just not completely sure whether this would imply that we are working towards an inclusive community.

> Fine with me. I agree with @JaGeo that I have no idea what inclusive means in this context. We don't select our community - they basically volunteer their PRs and Issue Reports. In most instances, we do not even know the real identity of our contributors.

To me, in this context inclusive has two dimensions. First, we seek a process whereby any of our contributors / community members (as opposed to only a closed or opaque small group) have an opportunity to see and provide feedback on our decisions if they choose, and second, that we take intentional steps to make sure our meetings, discussions, and tools are accessible, welcoming and respectful to contributors regardless of background.

What do y'all think? Is it helpful to be explicit about some of these points?

**Comment by JaGeo** [comment]
Yes, I think we should definitely be more explicit about each of the points (e.g., what do we mean by inclusive, what do we mean by community-driven and so on). As someone suggested in yesterday's meeting, maybe this is then the next step after having this sort of short summary of our mission.

I also agree that "inclusive" should refer to both of the points that you @rkingsbury mentioned.

**Comment by rkingsbury** [comment]
I typically think of mission statements as succinct, high-level statements of purpose for an organization. However it sounds like it's important to go a step further and explicitly clarify what we mean by "inclusive". This also suggests to me that we should explicitly clarify the other goals like "community-driven", "accountable", "transparent", and "coordinated"

To that end, I propose we keep the current mission statement as the first paragraph, then add 1-2 sentences below it to elaborate the meaning of each objective. I've updated the PR with a draft, which I'm copying below. @JaGeo - note that I absorbed one of the inclusive points into "transparent", but they are both there.

---

> The mission of the Materials Project Software Foundation is to provide **community-driven**, **inclusive**, **coordinated**, **transparent**, and **accountable** governance of select public-facing and open-source Materials Project software packages.

> We seek to be **community-driven** by considering the needs of a broad cross-section of our users when making development decisions.

> We seek to be **inclusive** by taking intentional steps to make our meetings, discussions, and tools accessible, welcoming and respectful to contributors regardless of background.

> We seek to be **coordinated** by promoting consistency and mutual compatibility among our codes, documentation, and training materials.

> We seek to be **transparent** by publicly documenting major development decisions and providing opportunities for community members to give feedback on them.

> We seek to be **accountable** by empowering Foundation members or users to alert us if they feel a development decision or misconduct within the community is undermining this mission.

**Pull request merged**
