### PR TITLE
Initial MP Software Foundation bylaws

### PR DESCRIPTION
**Pull request by rkingsbury**
This PR contains first draft bylaws to clarify how decisions are made and what they mean.

I highly recommend anyone unfamiliar to read this memo on Rough Consensus decision making from the Internet Engineering Task Force
https://www.rfc-editor.org/rfc/rfc7282

### CODE REVIEW

**Comment by rkingsbury** [comment]
I've revised the PR based on discussion at today's meeting. Additional comments are welcome!

**Comment by rkingsbury** [comment]
Based on some of the discussion last time, I'm going to propose here and alternate, voting-based decision making protocol. Let me know what you all think

## The Rough Consensus option (currently in PR)

### Making Decisions

1. During the meeting, the Chairperson will lead a discussion of each PR while the Notetaker captures significant points of agreement or disagreement and options considered.
2. The MPSF will make decisions according to the principle of "Rough Consensus" as described by the [Internet Engineering Task Force](https://www.rfc-editor.org/rfc/rfc7282#page-7). Rough Consensus makes a distinction between members seeing a "fundamental flaw" with a proposed decision vs. thinking an alternative is "not the best choice", as described [here](https://async.twist.com/decision-making-flat-organization/). E.g., “I don’t believe Solution A is the best choice, because XYZ. I believe Solution B would be better, but I accept that Solution A can work too.” vs. “I believe Solution A is unacceptable because XYZ.”
3. A vote of rough consensus can be called by the Chairperson. If there is unanimous agreement than rough consnesus is called. If there is not unanimous agreement, the Chairperson can decide to continue discussion, or if a majority believes rouch consensus has been achieved, the Chairperson can decide to call rough consensus provided that the associated MADR captures both majority and minority viewpoints.
4. If rough consensus has not emerged, the PR will be left open and revisited at the next meeting.
5. When rough consensus is called, the PR will be updated before the next MPSF meeting by its author and/or the Repository Keeper to capture the decision outcome and major discussion points (including minority viewpoints / major objections as appropriate). At the beginning of the next meeting, the Chairperson will make a final call for new objections, and then the PR will be merged, signifying its adoption as an MPSF recommendation. Only objections that are new and substantially different from those discussed in the previous meeting(s) would be grounds for preventing adoption.
6. If a PR has been discussed a 2nd time (i.e. at multiple meetings) and no consensus is reached, this should be recorded in the GitHub discussion and the PR will be closed.
7. Decision Records are not set in stone. They may be superceded or deprecated by future decisions at the discretion of the Steering Committee


## The Voting-based approach (alternate proposal)

### Making Decisions

1. During the meeting, the Chairperson will lead a discussion of each PR while the Notetaker captures significant points of agreement or disagreement and options considered.
2. The MPSF will make decisions guided by the principle of "Rough Consensus" as described by the [Internet Engineering Task Force](https://www.rfc-editor.org/rfc/rfc7282#page-7). Rough Consensus makes a distinction between members seeing a "fundamental flaw" with a proposed decision vs. thinking an alternative is "not the best choice", as described [here](https://async.twist.com/decision-making-flat-organization/). E.g., “I don’t believe Solution A is the best choice, because XYZ. I believe Solution B would be better, but I accept that Solution A can work too.” vs. “I believe Solution A is unacceptable because XYZ.”
3. The Chairperson will lead the discussion, trying to ensure that all alternatives and concerns are heard and debated within the group. When the Chairperson believes this has happened, they can call for a vote to adopt an alternative. 
4. If a member feels their concern has not been adequately heard, they may object to the vote. In this case, the member must explicitly re-state their concern and the Chairperson will extend the discussion to address that specific point. Members may only object to a vote one time per concern. In other words, if the same member wishes to object to a vote a second time, they must state a substantively different concern.
7. When a vote is taken and a majority has voted in favor, the PR will be updated before the next MPSF meeting by its author and/or the Repository Keeper to capture the decision outcome and major discussion points (including minority viewpoints / major objections as appropriate). At the beginning of the next meeting, the Chairperson will make a final call for new objections, and then the PR will be merged, signifying its adoption as an MPSF recommendation. Only objections that are new and substantially different from those discussed in the previous meeting(s) would be grounds for preventing adoption.
6. When a vote is taken and a majority does not vote in favor, the PR will be left open and revisited at the next meeting.
9. If a PR has been discussed a 2nd time (i.e. at multiple meetings) and not yet approved, this should be recorded in the GitHub discussion and the PR will be closed.
10. Decision Records are not set in stone. They may be superceded or deprecated by future decisions at the discretion of the Steering Committee

**Comment by Andrew-S-Rosen** [comment]
I wonder if we should be including Custodian under the list of included codes too?

**Comment by rkingsbury** [comment]
> I wonder if we should be including Custodian under the list of included codes too?

I think that would be great, but that is ultimately up to the custodian maintainers. In the initial discussions when we formed the MPSF, `custodian` and `fireworks` maintainers preferred to wait and see how our processes developed before committing to participating. That's why they aren't listed.

**Pull request merged**
