### PR TITLE
0007 - Highlighting MP-Adjacent Software

### PR DESCRIPTION
**Pull request by Andrew-S-Rosen**
There are several software packages that use or are built around the core Materials Project software stack. An incomplete list can be found in the Pymatgen docs [here](https://pymatgen.org/addons#external-tools), which includes the ones that rely on Pymatgen in particular.

The aim of this decision is to decide where and how MP-adjacent software will be highlighted with the main goals being:

1. Increasing visibility of MP-adjacent software
2. Preventing the development of redundant software
3. Advertising the impact of the Materials Project ecosystem

### CODE REVIEW

**Comment by JaGeo** [comment]
@arosen93 very much like it! Especially also because of point 3. 
Maybe, one could also present some additional statistics there on how many projects (github etc.) rely on the core codes of MP.

**Comment by janosh** [comment]
[We're at 242 `pymatgen`-dependent packages discovered on GH](https://github.com/materialsproject/pymatgen/network/dependents?dependent_type=PACKAGE).

**Comment by mkhorton** [comment]
For a long time I've wanted to add [`duecredit`](https://github.com/duecredit/duecredit) support to pymatgen. I ran out of steam while writing the PR, because there are a lot of DOIs!

I'm not sold on the intended use of duecredit (running a "credit" script to automatically give you a list of citations to cite), although I can see some people using it. I think the main advantage is that it gives a systematic way to associate DOIs with individual functions in a codebase, and this allows, for example, a documentation page to be automatically written that contains all of those DOIs.

**Comment by Andrew-S-Rosen** [comment]
Link to the Pymatgen PR for `duecredit`: https://github.com/materialsproject/pymatgen/pull/3107

**Comment by shyuep** [comment]
I think duecredit is a waste of time and does not increase visibility beyond what a documented reference would provide. I am fine if the original author of the method wants to add a duecredit decorator for their implemented method, but I am dead against any MP developer , eg @janosh , spending the effort to figure out what are the appropriate citations for each method and adding them. Pls remember that we have limited dev time and literally a thousand things that need to be fixed or implemented. This is not a fruitful use of time.

**Comment by janosh** [comment]
This is just to get the ball rolling and explore how well it works. I won't be hunting references down myself. I'm just converting all the existing DOIs in doc strings to `due.dcite` decorators.

**Comment by mkhorton** [comment]
I have no view on how MP team should spend their time, since I’m no longer accountable there.

To defend duecredit: however the list of dois is obtained and formalised, there *is* value in having a canonical list of papers, algorithms, etc. that are used by and cited within a code.

Having citations in-line in a docstring is perhaps sufficient ethically but it’s still useful to have one page where we can see everything. Think something like a “credits” page in the docs.

**Comment by shyuep** [comment]
Yes having a list of credits is important. But it is up to the contributor. If I decide that adding a function to add 1+1 is not worth adding a due credit, why should an MP dev add it for me? The onus is on the contributor.

**Comment by Andrew-S-Rosen** [comment]
Since this is on the PR I opened, I will add my personal $0.02 just for the sake of bookkeeping even though it's perhaps unnecessary.

My gut instinct is that most developers will not care enough to use `duecredit` and most users won't care enough to track down the citations with it. That said, since there's no harm per se in its inclusion, I have little opinion about what happens to existing DOIs (and what MP does with their time is also not mine to judge).

In general, my philosophy is that "everything should be as simple as possible and no simpler," and this is an example where added boilerplate will probably be ignored by most even though the intentions are good. If the user thinks to cite something (and that's perhaps a "big if"), they'll probably go to the relevant section of the docs for their imported module and that's it.

**Comment by janosh** [comment]
I'd say it's already half-way there so if @mkhorton can give feedback on https://github.com/materialsproject/pymatgen/pull/3107, I can do the rest and get it merged today. Then the time investment was minimal.

Maybe citations are like doc strings. Once they're all over the code, they become a habit since people tend to be guided by existing code.

**Comment by JaGeo** [comment]
I very much believe that developers will simply add the decorator once they find out that it is there!

**Comment by Andrew-S-Rosen** [comment]
I think that's a fair assessment. That said, how will users know about it and feel encouraged to use it? Presumably there will need to be something added to the docs in a visible way.

**Comment by rkingsbury** [comment]
> I very much believe that developers will simply add the decorator once they find out that it is there!

Agreed. Since all we have to do is add a single stub file to each repo in order to support this, I think it's worthwhile. Then contributors have the option to use it if they wish. If they don't (or they don't know about it), there's no harm done and nothing changes.

> I think that's a fair assessment. That said, how will users know about it and feel encouraged to use it? Presumably there will need to be something added to the docs in a visible way.

Definitely should be mentioned in the Contributor Guide, provided that we support it in several of our codes.

**Comment by rkingsbury** [comment]
A couple of notes that may relate to discussion:
1. There are still several TODO items on the[ public Contributor Guide](https://docs.materialsproject.org/community/getting-involved/contributor-guide). Maybe we should focus effort on addressing or removing those?
2. The [atomate2 workflow tutorial](https://materialsproject.github.io/atomate2/dev/workflow_tutorial.html) is not linked from the docs navigation as far as I can tell. You have to search for it.

**Comment by mkhorton** [comment]
Marked to merge, implementation to follow.

**Pull request merged**
