### PR TITLE
0011 - Python version support policy

### PR DESCRIPTION
**Pull request by rkingsbury**
Proposing a policy on python version support

### CODE REVIEW

**Comment by mkhorton** [comment]
+1 for [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) for all our codes, i.e. we follow whatever is recommended in their "Support Table".

**Comment by shyuep** [comment]
Instead of us coming up with a policy, I would suggest a simple one - we will support whatever Python version that the latest scientific python stack, esp numpy, supports. If they drop support for a version, we drop support. Then we don't need to worry about figuring out all these on our own. In the end, our codes are built on these packages. We cannot follow a different policy anyway.

**Comment by mkhorton** [comment]
Notes for suggested decision:

* Intent is to set expectations for maintainer's responsibility, and for user of the code.
* We will commit to support the same versions of Python as numpy (NEP 29).
* Additional versions of Python _may_ work, but fixes are not expected. If an unsupported version of Python is tested in CI, and breaks, it will be removed from CI.
* When support for major Python version is dropped, there should be one final release before updating the minimum Python version specified in the project metadata (setup.py/pyproject.toml) that can incorporate any fixes when possible. The changelog must report that support for a major Python version has been removed when it is removed.

@rkingsbury to implement changes to this PR to reflect this suggested decision.

**Comment by rkingsbury** [comment]
Updated with outcome of today's meeting @mkhorton . Let me know if other changes are needed before merge!

All - by way of implementing this policy, please plan to start adding python 3.12+ support to your CI pipelines

**Pull request merged**
